### ISSUE TITLE
Missing search term: shadow

### ISSUE THREAD

**Issue by profpandabear** [Leidwesen/SearchPhrases#2]
Unlike `rocket`, `shadow` includes  research shadow pokemon. I don't remember when this was implemented, but it was fairly early on...

**Comment by Leidwesen** [comment]
It's not the clearest, but (to save space) it is listed under "`{keyword}`: Options: legendary, mythical, 'ultra beasts', **shadow**, purified, shiny, lucky."

**Comment by profpandabear** [comment]
Hmm... perhaps listing it as a workaround?

**Comment by Leidwesen** [comment]
That's a valid request, should be addressed by a8a44b2.
