### ISSUE TITLE
Suggestion for the notes about the "mega{N}" entry

### ISSUE THREAD

**Issue by fluffbutter** [Leidwesen/SearchPhrases#4]
On the Phrases page, under the "pokemon - ranges" category, I have a suggestion about the "mega" entry. In the notes, you say, 

> 'mega0' finds only pokemon capable of mega evolution.

To me that sounds like ALL the pokemon capable of mega evolution, when "mega0," finds all the pokemon that can mega evolve that have NOT already been mega evolved. I'd change the search term to, "mega0-" reword the note to include the caveat, or just take out that example.

If you're trying to convey that the mega term will return only pokemon that have a mega evolution in the game, maybe try this as the note:

> Always returns only pokemon that have a mega evolution. 
> 0=never mega evolved, 1/2/3 = Base/High/Max mega level.
> 'mega1-' finds all previously mega evolved pokemon.
> [Bug]: negated 'mega{N}' only returns pokemon capable of mega evolution, instead of all pokemon.

IMO, I think you just need the bottom three lines. 

Btw, I LOVE this page! It is complete, organized, and easy to follow. All that prose people use to explain the search strings is garbage. The nerd in me is delighted!

**Comment by Leidwesen** [comment]
My thought process was probably along the lines of "mega0 means [never mega evolved], but aren't every other non-mega-eligible pokemon never mega evolved? Should probably clarify that".

But I think that it's covered well enough in the Bug line, so I fixed things up similar to your suggestion with [72332d5](https://github.com/Leidwesen/SearchPhrases/commit/72332d56dfadb4fa33778da832c0f9f23a6a59c2)

Thanks for the feedback :) Let me know if there's any other wording which could be improved.

**Comment by fluffbutter** [comment]
Looks good!

Happy to help.
