### ISSUE TITLE
 Region search tags (eg "kanto", "johto") now exclude other regional variants 

### ISSUE THREAD

**Issue by nicolasmaia** [Leidwesen/SearchPhrases#5]
Not my discovery, but here it is, in case you were unaware:
https://www.reddit.com/r/TheSilphRoad/comments/1ga2x4v/region_search_tags_eg_kanto_johto_now_exclude/

**Comment by Leidwesen** [comment]
Thanks for letting me know! It'll take a bit to get things properly updated, especially since this update appears to have some issues of its own.

**Comment by Leidwesen** [comment]
These changes are still live a month and several versions later, so I suspect they're here to stay. I've updated the site to confirm this behavior and its bugs in [5b30165](https://github.com/Leidwesen/SearchPhrases/commit/5b301657e51e286f80c833d41241c69c9da972a4).
